# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: sydia1103
description: Advanced computer projects
seo_paginator_message: "%<current>s / %<total>s | "
name: Test
author: Test
email: a@a.com
legal: '&copy; 2006-2022 Test. All rights reserved.'
description_long: >- # this means to ignore newlines until "baseurl:"
  My name is Test. Read more about who I am 
  <a href="/about">here</a>.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sydia1103.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: sydia1103
header_pages:
  - about.md
paginate: 8
paginate_path: "/:num/"
show_excerpts: true
disqus:
  shortname: sydia1103
projects:
  limit: 7
  exclude:
    archived: false
    forks: true
    projects:
    - sydia1103.github.io
    - sydia
    # - repo-name

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-octicons
minima:
  skin: custom
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
